branch-defaults:
  main:
    environment: spotifyvstheworld-server-dev
    group_suffix: null
environment-defaults:
  spotifyvstheworld-server-dev:
    branch: main
    repository: beanstalk-test
global:
  application_name: spotifyvstheworld-server
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: beanstalk-test
  sc: git
  workspace_type: Application
